
from typing import Literal

STATUS_AVAILABLE = 'Available'
STATUS_BORROWED = 'Borrowed'

class Book :
    def __init__(self, ID, title, author, status: Literal['Available', 'Borrowed'] = STATUS_AVAILABLE) :
        self.ID = ID
        self.title = title
        self.author = author
        self.status = status
    
    def borrow_book(self) :
        self.status = STATUS_BORROWED
    def return_book(self) :
        self.status = STATUS_AVAILABLE
    
    def get_status(self) -> str :
        return self.status
    
    def __str__(self):
        def cut_str(s : str, max_len : int) -> str :
            if len(s) > max_len :
                return s[:max_len-3] + "..."
            else :
                return s
        return f"{self.ID:>8}: {cut_str(self.title, 25):<25s} {cut_str(self.author, 15):<15s} - Status: {self.get_status()}"
    
class Library :
    def __init__(self) :
        self.books : list[Book] = []
        self.idxs = {}
    def __getitem__(self, idx) :
        return self.books[idx]
    def add_book(self, book : Book) :
        self.books.append(book)
        self.idxs[book.ID] = len(self.books) - 1
    def borrow_book(self, id) :
        if id not in self.idxs :
            print(f"Book with ID {id} not found in library")
            return
        book : Book = self.books[self.idxs[id]]
        if book.get_status() == STATUS_BORROWED :
            print("Not available")
        else :
            book.borrow_book()
    def return_book(self, id) :
        if id not in self.idxs :
            print(f"Book with ID {id} not found in library")
            return 
        book : Book = self.books[self.idxs[id]]
        if book.get_status() == STATUS_AVAILABLE :
            print("Book is already available")
        else :
            book.return_book()
    def list_available_books(self) :
        avail_books = [book for book in self.books if book.get_status() == STATUS_AVAILABLE]
        avail_books = sorted(avail_books, key=lambda book : book.ID)
        
        print(f"{'ID' :>8}: {'Title' :<25s} {'Author':<15s} - {'Status'}")
        for book in avail_books :
            print(book)

if __name__ == "__main__" :
    """
Test suite for Q2.py - Library Management System
Covers:
  1. Normal operations (add, borrow, return, list, index)
  2. Edge cases identified in code review:
     - borrow_book() with non-existent ID  -> KeyError (known bug)
     - return_book() with non-existent ID  -> KeyError (known bug)
     - return_book() on a non-borrowed book (no error, silent overwrite)
     - title truncation in __str__ for titles > 25 characters
"""

import traceback
from Q2 import Book, Library, STATUS_AVAILABLE, STATUS_BORROWED

PASS = "\033[92m[PASS]\033[0m"
FAIL = "\033[91m[FAIL]\033[0m"
WARN = "\033[93m[WARN]\033[0m"

def check(description, condition, warn=False):
    tag = WARN if (warn and not condition) else (PASS if condition else FAIL)
    print(f"  {tag} {description}")
    return condition

if __name__ == "__main__":
    print("=" * 60)
    print("Test Suite from me")
    print("=" * 60)
    lib = Library()
    lib.add_book(Book(2, "test title1", "test author1"))
    lib.add_book(Book(1, "test title2", "test author2"))
    lib.add_book(Book(6, "test title3", "test author3"))
    lib.add_book(Book(114, "test title114", "test author114"))
    
    lib.list_available_books()
    
    lib.borrow_book(6)
    
    lib.list_available_books()
    
    lib.borrow_book(1)
    
    lib.list_available_books()
    
    lib.borrow_book(1) # should print 'Not available'
    lib.return_book(6)
    
    lib.list_available_books()
    
    print(f'book[1]: {lib[1]}')
    
    lib.add_book(Book(101, "To Kill a Mockingbird", "Harper Lee"))

    print(f"book[4]: {lib[4]}")
    lib.list_available_books()

    # test cases generated by Manus

    print("=" * 60)
    print("Test Suite by Manus")
    print("=" * 60)

    # ----------------------------------------------------------------
    # Section 1: Book class basic behaviour
    # ----------------------------------------------------------------
    print("\n[Section 1] Book class basic behaviour")

    b = Book(1, "1984", "George Orwell")
    check("Initial status is 'Available'", b.get_status() == STATUS_AVAILABLE)
    check("__str__ contains ID, title, author, status",
        "1984" in str(b) and "George Orwell" in str(b) and "Available" in str(b))

    b.borrow_book()
    check("After borrow_book(), status is 'Borrowed'", b.get_status() == STATUS_BORROWED)

    b.return_book()
    check("After return_book(), status is 'Available'", b.get_status() == STATUS_AVAILABLE)

    # ----------------------------------------------------------------
    # Section 2: Normal Library operations
    # ----------------------------------------------------------------
    print("\n[Section 2] Normal Library operations")

    lib = Library()
    b1 = Book(2,   "test title1",         "test author1")
    b2 = Book(1,   "test title2",         "test author2")
    b3 = Book(6,   "test title3",         "test author3")
    b4 = Book(114, "test title114",       "test author114")

    lib.add_book(b1)
    lib.add_book(b2)
    lib.add_book(b3)
    lib.add_book(b4)

    check("Library contains 4 books after adding", len(lib.books) == 4)

    # list_available_books should show all 4 in ID order
    avail = [book for book in lib.books if book.get_status() == STATUS_AVAILABLE]
    avail_sorted = sorted(avail, key=lambda b: b.ID)
    check("All 4 books available initially", len(avail_sorted) == 4)
    check("list_available_books returns books in ID ascending order",
        [b.ID for b in avail_sorted] == sorted([b.ID for b in avail_sorted]))

    # Borrow book with ID 6
    lib.borrow_book(6)
    check("After borrowing ID=6, status is 'Borrowed'", lib.books[lib.idxs[6]].get_status() == STATUS_BORROWED)

    avail2 = [book for book in lib.books if book.get_status() == STATUS_AVAILABLE]
    check("3 books available after borrowing one", len(avail2) == 3)

    # Borrow again (should print "Not available")
    print("  [INFO] Borrowing ID=6 again (expect 'Not available' message):")
    print("  ", end="")
    lib.borrow_book(6)
    check("Status unchanged after double-borrow attempt", lib.books[lib.idxs[6]].get_status() == STATUS_BORROWED)

    # Return book
    lib.return_book(6)
    check("After return_book(6), status is 'Available'", lib.books[lib.idxs[6]].get_status() == STATUS_AVAILABLE)

    # __getitem__
    check("Library[0] returns first book added (ID=2)", lib[0].ID == 2)
    check("Library[1] returns second book added (ID=1)", lib[1].ID == 1)

    # ----------------------------------------------------------------
    # Section 3: Edge case — borrow non-existent ID (known bug)
    # ----------------------------------------------------------------
    print("\n[Section 3] Edge case — borrow_book() with non-existent ID")

    try:
        lib.borrow_book(9999)
        check("borrow_book(9999) did NOT raise an exception (handled gracefully)", True)
    except KeyError as e:
        check("borrow_book(9999) raises KeyError — ID not found (unhandled, known bug)", False, warn=True)
        print(f"         KeyError: {e}")

    # ----------------------------------------------------------------
    # Section 4: Edge case — return non-existent ID (known bug)
    # ----------------------------------------------------------------
    print("\n[Section 4] Edge case — return_book() with non-existent ID")

    try:
        lib.return_book(9999)
        check("return_book(9999) did NOT raise an exception (handled gracefully)", True)
    except KeyError as e:
        check("return_book(9999) raises KeyError — ID not found (unhandled, known bug)", False, warn=True)
        print(f"         KeyError: {e}")

    # ----------------------------------------------------------------
    # Section 5: Edge case — return a book that was never borrowed
    # ----------------------------------------------------------------
    print("\n[Section 5] Edge case — return_book() on a non-borrowed book")

    # b1 (ID=2) is currently Available
    status_before = lib.books[lib.idxs[2]].get_status()
    lib.return_book(2)  # Should ideally warn, but currently silently succeeds
    status_after = lib.books[lib.idxs[2]].get_status()
    check("Returning a non-borrowed book does not crash", True)
    check("Status remains 'Available' after returning a non-borrowed book (silent overwrite)",
        status_after == STATUS_AVAILABLE, warn=True)
    print(f"         [INFO] No warning is printed — silent state overwrite (known minor issue)")

    # ----------------------------------------------------------------
    # Section 6: Edge case — title truncation in __str__
    # ----------------------------------------------------------------
    print("\n[Section 6] Edge case — title > 25 characters in __str__")

    long_title = "A Very Long Book Title That Exceeds Limit"  # 41 chars
    b_long = Book(999, long_title, "Some Author")
    str_repr = str(b_long)
    check("Book with long title does not crash __str__", True)
    check("Long title is silently truncated to 25 chars (no ellipsis indicator)",
        long_title[:22] in str_repr and long_title not in str_repr, warn=True)
    print(f"         __str__ output: '{str_repr.strip()}'")
    print(f"         Original title: '{long_title}' ({len(long_title)} chars)")

    # ----------------------------------------------------------------
    # Summary
    # ----------------------------------------------------------------
    print("\n" + "=" * 60)
    print("Test run complete.")
    print(f"  {PASS} = Passed    {FAIL} = Failed    {WARN} = Known issue / warning")
    print("=" * 60)